name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t hannahanto/my-flask-app:latest .
          docker tag hannahanto/my-flask-app:latest hannahanto/my-flask-app:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.PYTHON }}" | docker login -u hannahanto --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push hannahanto/my-flask-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull saralaaa/pythonapi:latest

      - name: Stop Existing Container
        run: docker stop pythonapi_container || true

      - name: Remove Existing Container
        run: docker pythonapi_container || true

      - name: Deploy Docker Container
        run: docker run -d -p 5000:5000 --name pythonapi_container saralaaa/pythonapi:latest
